[package]
name = 'chainbridge'
version = '0.0.1'
authors = ['david@chainsafe.io']
edition = '2018'

[dependencies]
# third-party dependencies
codec = { package = "parity-scale-codec", version = "1.3.4", default-features = false, features = ["derive"] }
serde = { version = "1.0.102", optional = true }

# primitives
sp-std = { version = "2.0.0-rc6", git = "https://github.com/centrifuge/substrate.git", rev = "dfa6998ad31f1430a54ef1bce2722a7cf2795cff", default-features = false }
sp-runtime = { version = "2.0.0-rc6", git = "https://github.com/centrifuge/substrate.git", rev = "dfa6998ad31f1430a54ef1bce2722a7cf2795cff", default-features = false }
sp-io = { version = "2.0.0-rc6", git = "https://github.com/centrifuge/substrate.git", rev = "dfa6998ad31f1430a54ef1bce2722a7cf2795cff", default-features = false }
sp-core = { version = "2.0.0-rc6", git = "https://github.com/centrifuge/substrate.git", rev = "dfa6998ad31f1430a54ef1bce2722a7cf2795cff", default-features = false }

# frame dependencies
frame-support = { version = "2.0.0-rc6", git = "https://github.com/centrifuge/substrate.git", rev = "dfa6998ad31f1430a54ef1bce2722a7cf2795cff", default-features = false }
frame-system = { version = "2.0.0-rc6", git = "https://github.com/centrifuge/substrate.git", rev = "dfa6998ad31f1430a54ef1bce2722a7cf2795cff", default-features = false }

pallet-balances = { version = "2.0.0-rc6", git = "https://github.com/centrifuge/substrate.git", rev = "dfa6998ad31f1430a54ef1bce2722a7cf2795cff", default-features = false }

[build-dependencies]
wasm-builder-runner = { version = "1.0.5", package = "substrate-wasm-builder-runner", git = "https://github.com/centrifuge/substrate.git", rev = "dfa6998ad31f1430a54ef1bce2722a7cf2795cff" }
[features]
default = ["std"]
std = [
	"codec/std",
	"serde",
	"sp-std/std",
	"sp-runtime/std",
    "sp-io/std",
    "sp-core/std",
	"frame-support/std",
	"frame-system/std",
	"pallet-balances/std",
]
